name: Deploy Backend to Azure Web App

on:
  push:
    branches:
      - main
    # paths:
    #   - 'backend_webapp/**'   # ya jo tera folder hai

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd backend_webapp
          pip install -r requirements.txt

      - name: Zip artifact
        run: |
          cd backend_webapp
          zip -r release.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: dev-todoapp-backend-web-lav
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
          package: backend_webapp/release.zip